version: '3.9'

services:
  db:
    image: postgres:16.0-alpine3.17
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine3.18
    container_name: todo-redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    restart: unless-stopped
  