version: '3.9'

services:
  db:
    image: postgres:16.0-alpine3.17
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
  